#ifndef UI_TELA_MSG_FUNCIONARIOS_H
#define UI_TELA_MSG_FUNCIONARIOS_H

void ui_desenhar_tela_msg_adicionar_funcionario_sucesso(void);
void ui_desenhar_tela_msg_adicionar_funcionario_falha(void);
void ui_desenhar_tela_msg_adicionar_funcionario_ja_existe(void);

#endif // UI_TELA_MSG_FUNCIONARIOS_H